gnomad_common: "resources/af-only-gnomad.hg38.p001_biallelic_snps.vcf"
giab_hc_bed: "resources/GRCh38_notinalldifficultregions.bed"
reference: "/.mounts/labs/simpsonlab/data/references/GRCh38_no_alt_analysis_set.GCA_000001405.15.fna"
smrest: "/.mounts/labs/simpsonlab/users/jsimpson/code/smrest/target/release/smrest"
